- name: Install pip
  become: yes
  apt:
    name: python3-pip
    state: latest



- name: Install python dependency
  become: yes
  command: pip3 install {{item}}
  with_items:
    - CouchDB==1.2
    - Django==2.0.5
    - pytz==2018.4
